"use client";

import { useCallback, useEffect, useState } from "react";
import { Eye, Mail, Search, Trash2, X } from "lucide-react";
import { deleteAdminLead, getAdminLead, listAdminLeads, updateAdminLeadStatus, type Lead, type LeadStatus } from "@/lib/api/leads";
import styles from "@/components/admin/projects/projects.module.css";
import local from "./leads.module.css";

export default function LeadInbox() {
  const [leads, setLeads] = useState<Lead[]>([]); const [search, setSearch] = useState(""); const [status, setStatus] = useState("");
  const [page, setPage] = useState(1); const [pages, setPages] = useState(1); const [total, setTotal] = useState(0); const [newCount, setNewCount] = useState(0);
  const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [success, setSuccess] = useState("");
  const [detail, setDetail] = useState<Lead | null>(null); const [detailLoading, setDetailLoading] = useState(false); const [deleting, setDeleting] = useState<Lead | null>(null);
  const load = useCallback(async () => { setLoading(true); setError(""); try { const result = await listAdminLeads({ search, status, page }); setLeads(result.leads); setPages(Math.max(result.pagination.pages, 1)); setTotal(result.pagination.total); setNewCount(result.counts.new); } catch (loadError) { setError(loadError instanceof Error ? loadError.message : "Leads could not be loaded"); } finally { setLoading(false); } }, [page, search, status]);
  useEffect(() => { const timer = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(timer); }, [load]);
  async function view(id: string) { setDetailLoading(true); setError(""); try { setDetail(await getAdminLead(id)); } catch (viewError) { setError(viewError instanceof Error ? viewError.message : "Lead could not be loaded"); } finally { setDetailLoading(false); } }
  async function changeStatus(nextStatus: LeadStatus) { if (!detail) return; try { const updated = await updateAdminLeadStatus(detail.id, nextStatus); setDetail(updated); setSuccess("Lead status updated."); await load(); } catch (updateError) { setError(updateError instanceof Error ? updateError.message : "Status could not be updated"); } }
  async function confirmDelete() { if (!deleting) return; try { await deleteAdminLead(deleting.id); setSuccess(`Lead from “${deleting.name}” was deleted.`); if (detail?.id === deleting.id) setDetail(null); setDeleting(null); await load(); } catch (deleteError) { setError(deleteError instanceof Error ? deleteError.message : "Lead could not be deleted"); setDeleting(null); } }

  return <div><header className={styles.pageHeader}><div><p className={styles.eyebrow}>Inbox</p><h1>Contact leads</h1><p>Review website enquiries and update their follow-up status.</p></div><div className={local.counts}><span><strong>{newCount}</strong> New</span><span><strong>{total}</strong> Results</span></div></header>
    {success && <div className={local.success} role="status">{success}<button onClick={() => setSuccess("")} type="button">Dismiss</button></div>}
    <section className={styles.panel}><div className={styles.filters}><label className={styles.search}><Search size={15} /><input aria-label="Search leads" onChange={(e) => { setPage(1); setSearch(e.target.value); }} placeholder="Search name, email, company, subject…" value={search} /></label><select aria-label="Filter by status" onChange={(e) => { setPage(1); setStatus(e.target.value); }} value={status}><option value="">All statuses</option><option value="new">New</option><option value="contacted">Contacted</option><option value="closed">Closed</option></select><span className={styles.total}>{total} total</span></div>
      {error && <div className={styles.error} role="alert">{error}<button onClick={() => void load()} type="button">Try again</button></div>}
      {loading ? <div className={styles.state}>Loading leads…</div> : leads.length === 0 ? <div className={styles.state}><strong>No leads found</strong><span>New website enquiries will appear here.</span></div> : <div className={styles.tableWrap}><table className={`${styles.table} ${local.table}`}><thead><tr><th>Name</th><th>Email</th><th>Company</th><th>Subject</th><th>Status</th><th>Received</th><th><span className={styles.srOnly}>Actions</span></th></tr></thead><tbody>{leads.map((lead) => <tr key={lead.id}><td><strong>{lead.name}</strong></td><td><a className={local.email} href={`mailto:${lead.email}`}>{lead.email}</a></td><td>{lead.company || "—"}</td><td className={local.subject}>{lead.subject || "—"}</td><td><span className={`${styles.badge} ${local[lead.status]}`}>{lead.status}</span></td><td>{new Intl.DateTimeFormat(undefined, { dateStyle: "medium" }).format(new Date(lead.createdAt))}</td><td><div className={styles.rowActions}><button aria-label={`View ${lead.name}`} onClick={() => void view(lead.id)} type="button"><Eye size={15} /></button><button aria-label={`Delete ${lead.name}`} onClick={() => setDeleting(lead)} type="button"><Trash2 size={15} /></button></div></td></tr>)}</tbody></table></div>}
      <div className={styles.pagination}><button disabled={page <= 1 || loading} onClick={() => setPage((value) => value - 1)} type="button">Previous</button><span>Page {page} of {pages}</span><button disabled={page >= pages || loading} onClick={() => setPage((value) => value + 1)} type="button">Next</button></div></section>
    {detailLoading && <div className={local.drawerBackdrop}><aside className={local.drawer}><div className={styles.state}>Loading lead…</div></aside></div>}
    {detail && <div className={local.drawerBackdrop} role="presentation"><button aria-label="Close lead details" className={local.backdropDismiss} onClick={() => setDetail(null)} type="button" /><aside aria-labelledby="lead-detail-title" aria-modal="true" className={local.drawer} role="dialog"><header><div><span>Contact enquiry</span><h2 id="lead-detail-title">{detail.name}</h2></div><button aria-label="Close" onClick={() => setDetail(null)} type="button"><X size={18} /></button></header><div className={local.detailBody}><div className={local.statusRow}><label>Status<select onChange={(e) => void changeStatus(e.target.value as LeadStatus)} value={detail.status}><option value="new">New</option><option value="contacted">Contacted</option><option value="closed">Closed</option></select></label><a href={`mailto:${detail.email}`}><Mail size={15} /> Email lead</a></div><dl><div><dt>Email</dt><dd><a href={`mailto:${detail.email}`}>{detail.email}</a></dd></div><div><dt>Phone</dt><dd>{detail.phone || "Not provided"}</dd></div><div><dt>Company</dt><dd>{detail.company || "Not provided"}</dd></div><div><dt>Subject</dt><dd>{detail.subject || "Not provided"}</dd></div><div><dt>Source</dt><dd>{detail.source || "Not provided"}</dd></div><div><dt>Submitted</dt><dd>{new Intl.DateTimeFormat(undefined, { dateStyle: "long", timeStyle: "short" }).format(new Date(detail.createdAt))}</dd></div></dl><section><h3>Message</h3><p>{detail.message}</p></section><button className={local.deleteDetail} onClick={() => setDeleting(detail)} type="button"><Trash2 size={15} /> Delete lead</button></div></aside></div>}
    {deleting && <div className={styles.modalBackdrop} role="presentation"><div aria-labelledby="delete-lead-title" aria-modal="true" className={styles.modal} role="dialog"><h2 id="delete-lead-title">Delete lead?</h2><p>The enquiry from “{deleting.name}” will be permanently removed.</p><div><button className={styles.secondaryButton} onClick={() => setDeleting(null)} type="button">Cancel</button><button className={styles.dangerButton} onClick={() => void confirmDelete()} type="button">Delete lead</button></div></div></div>}
  </div>;
}
